services:
  dev:
    build:
      context: .
      target: dev
    ports:
      - '7004:7004'
      - '8004:8004'
      - '9000:9000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/backend/node_modules
      - /app/packages/eslint-config/node_modules
