services:
  dev:
    build:
      context: .
      target: dev
    ports:
      - '7004:7004'
      - '8004:8004'
      - '9000:9000'
    volumes:
      - .:/app
      # - ./apps/backend/src:/app/apps/backend/src:ro
      # - ./apps/frontend/src:/app/apps/frontend/src:ro
      - /app/node_modules
    # develop:
    #   watch:
    #     - path: ./Dockerfile
    #       action: rebuild

    #     - path: ./src
    #       action: sync+restart
    #       target: /app/src
    #       initial_sync: true
