GET http://localhost:8004/api/v0/products/
###

GET http://localhost:8004/api/v0/products/103/
###

POST http://localhost:8004/api/v0/products/103/
content-type: application/json

{"key":"ooooo","value":"ooooo"}
###

PATCH http://localhost:8004/api/v0/products/103/
content-type: application/json

# {"bad":"xxxxx","qwe":"xxxxx"}
{"key":"xxxxx","value":"xxxxx"}
###

DELETE http://localhost:8004/api/v0/products/103/
###
