GET http://localhost:8004/api/v0/sessions/
cookie: sessionId=abcdef
###
GET http://localhost:8004/api/v0/sessions/11/
cookie: sessionId=abcdef
###
DELETE http://localhost:8004/api/v0/sessions/12/
cookie: sessionId=abcdef
###
POST http://localhost:8004/api/v0/sessions/
cookie: sessionId=abcdef
content-type: application/json

{"nickname":"admin"}
###

PATCH http://localhost:8004/api/v0/sessions/11/
cookie: sessionId=abcdef
content-type: application/json

{"nickname":"admin"}
###
###

###
###
###
### AuthN PROBLEMS

GET http://localhost:8004/api/v0/sessions/
cookie: sessionId=xxx
###
GET http://localhost:8004/api/v0/sessions/11/
cookie: sessionId=xxx
###
DELETE http://localhost:8004/api/v0/sessions/11/
cookie: sessionId=xxx
###
POST http://localhost:8004/api/v0/sessions/
cookie: sessionId=xxx
content-type: application/json

{"nickname":"admin"}
###

PATCH http://localhost:8004/api/v0/sessions/11/
cookie: sessionId=xxx
content-type: application/json

{"nickname":"admin"}
###
###

###
###
###
### AuthZ PROBLEMS

GET http://localhost:8004/api/v0/sessions/
cookie: sessionId=fedcba
###
GET http://localhost:8004/api/v0/sessions/11/
cookie: sessionId=fedcba
###
DELETE http://localhost:8004/api/v0/sessions/11/
cookie: sessionId=fedcba
###
POST http://localhost:8004/api/v0/sessions/
cookie: sessionId=fedcba
content-type: application/json

{"nickname":"admin"}
###

PATCH http://localhost:8004/api/v0/sessions/11/
cookie: sessionId=fedcba
content-type: application/json

{"nickname":"admin"}
###
###

###
###
###
### Path WRONG

GET http://localhost:8004/api/v0/sessions/66/
cookie: sessionId=abcdef
###
DELETE http://localhost:8004/api/v0/sessions/66/
cookie: sessionId=abcdef
###
PATCH http://localhost:8004/api/v0/sessions/66/
cookie: sessionId=abcdef
content-type: application/json

{"nickname":"admin"}
###
###

###
###
###
### Payload WRONG

PATCH http://localhost:8004/api/v0/sessions/11/
content-type: application/json

{"nickname":-321}
### BAD
POST http://localhost:8004/api/v0/sessions/
content-type: application/json

{"nickname":false}
### BAD
PATCH http://localhost:8004/api/v0/sessions/11/
content-type: application/json

{,}
### BAD
POST http://localhost:8004/api/v0/sessions/
content-type: application/json

{,}
### BAD

GET http://localhost:8004/api/v0/sessions/1001/foo/321/
###
DELETE http://localhost:8004/api/v0/sessions/1001/foo/321/
###
