GET http://localhost:8004/api/v0/users/
###

GET http://localhost:8004/api/v0/users/111/
###

POST http://localhost:8004/api/v0/users/111/
content-type: application/json

{"nickname":"ooooooo","password":"ooooooo","email":"qqq"}
###

PATCH http://localhost:8004/api/v0/users/111/
content-type: application/json

# {"bad":"xxxxx","qwe":"xxxxx"}
{"money":11111,"password":"ooooooo","email":"qqq"}
###

DELETE http://localhost:8004/api/v0/users/111/
###
