GET http://localhost:8004/api/v0/users/
###
GET http://localhost:8004/api/v0/users/111/
###
DELETE http://localhost:8004/api/v0/users/111/
###

POST http://localhost:8004/api/v0/users/
content-type: application/json

{"nickname":"ooo","password":"ooooo","email":"ooo@ooo.oo"}
###

PATCH http://localhost:8004/api/v0/users/111/
content-type: application/json

{"money":12345,"password":"xxxxx"}
###
###


POST http://localhost:8004/api/v0/users/
content-type: application/json

{"nickname":"ooooooooo","password":"oooo","email":"ooo@ooooo"}
### BAD

PATCH http://localhost:8004/api/v0/users/111/
content-type: application/json

{"money":"12345","password":0}
### BAD
