name: cd
on: [push]
jobs:
  cd:
    # needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            #!/usr/bin/bash
            set -euo pipefail
            cd /srv/app
            wget -O docker-compose.prod.yml https://raw.githubusercontent.com/yourock1988/app-things/refs/heads/master/docker-compose.prod.yml
            docker compose -f docker-compose.prod.yml up --detach
