name: ci-cd
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: docker/setup-buildx-action@v4

      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v7
        with:
          context: .
          target: check
          push: false
          cache-to: type=gha,mode=max
          cache-from: type=gha

      - uses: docker/build-push-action@v7
        with:
          context: .
          target: prod
          push: true
          tags: ghcr.io/${{ github.repository }}/app-things:latest
          cache-to: type=gha,mode=max
          cache-from: type=gha

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            #!/usr/bin/bash
            set -euo pipefail
            cd /srv/app
            wget -O docker-compose.deploy.yml https://raw.githubusercontent.com/yourock1988/app-things/refs/heads/master/docker-compose.deploy.yml
            docker compose -f docker-compose.deploy.yml up -d --force-recreate --remove-orphans
            rm -f docker-compose.deploy.yml
